### PR TITLE
[#16] Update Stretch Goals

### PR DESCRIPTION
**Pull request by aaronhsli**
Added Stretch Goals to our .md file.

### CODE REVIEW

**Comment by aaronhsli** [comment]
[#16] was added to the commit message.

**Comment by amosyu2000** [comment]
Please amend the commit message as well.

**Comment by aaronhsli** [comment]
Amended the last commit to include the issue number in the commit message.

**Comment by aaronhsli** [comment]
Amended the last commit to include the issue number in the commit message.

**Review by amosyu2000 — APPROVED** [review]

**Review by MannyLemos — APPROVED** [review]

**Pull request merged**
