### PR TITLE
[#39] Create SRS Document (markdown)

### PR DESCRIPTION
**Pull request by MannyLemos**

### CODE REVIEW

**Review by amoscheung99527 — APPROVED** [review]

**Review by amosyu2000 — CHANGES_REQUESTED** [review]
Why don't we just use markdown for the sections? It would be a lot cleaner than HTML. e.g.
```
# Table of Contents
- [**1 Reference Material**](#1-reference-material)
  - [1.1 Table of Units](#11-table-of-units)

## 1 Reference Material
This section records information for easy reference.
### 1.1 Table of Units
add content
```

# Table of Contents
- [**1 Reference Material**](#1-reference-material)
  - [1.1 Table of Units](#11-table-of-units)

## 1 Reference Material
This section records information for easy reference.
### 1.1 Table of Units
add content

**Comment by MannyLemos** [comment]
@amosyu2000 Using markdown for the actual content breaks the linking when you export to pdf or view through preview. Not sure why...

looks like:
- [**1 Reference Material**](<#1 Reference Material>)
...
# 1 Reference Material

**Comment by amosyu2000** [comment]
> # Table of Contents
> - [**1 Reference Material**](#1-reference-material)
>   - [1.1 Table of Units](#11-table-of-units)
> 
> ## 1 Reference Material
> This section records information for easy reference.
> ### 1.1 Table of Units
> add content

Odd, it works for me. 
image
Do you have a screenshot?

**Comment by MannyLemos** [comment]
I was including spaces which i guess messes it up. I followed your method and it works. will upload shortly

**Comment by MannyLemos** [comment]
@amosyu2000 have updated lmk if better

**Comment by amosyu2000** [comment]
> @amosyu2000 have updated lmk if better

Looks great! Good work :)

**Review by amosyu2000 — APPROVED** [review]

**Pull request merged**
