### PR TITLE
[#218] [#220] Adding Moduel Hierarchy

### PR DESCRIPTION
**Pull request by amoscheung99527**

### CODE REVIEW

**Review by amosyu2000 — CHANGES_REQUESTED** [review]
Please update the Table of Contents
https://github.com/amosyu2000/cyclops/wiki/Contributing-Guide#41-if-you-edited-markdown-files

**Review by amosyu2000 — CHANGES_REQUESTED** [review]
See my other comment

**Review by amosyu2000 — APPROVED** [review]
Great work!

**Review by MannyLemos — APPROVED** [review]
this is a certified moment in history

**Pull request closed without merging**
