### PR TITLE
[#8] Updated CONTRIBUTING.md with more info

### PR DESCRIPTION
**Pull request by amosyu2000**
Things added:
- Table of Contents
- Created "Reviewing A Pull Request" section
- Small fixes

### CODE REVIEW

**Comment by aaronhsli** [comment]
Looks good, Amos!

**Review by aaronhsli — APPROVED** [review]
Looks good, Amos Yu!

**Comment by amosyu2000** [comment]
> 

kekW

**Review by amoscheung99527 — APPROVED** [review]
looks good to me

**Pull request merged**
