### PR TITLE
[#11] Update license

### PR DESCRIPTION
**Pull request by amoscheung99527**
updated the name of the license for this project.

### CODE REVIEW

**Comment by amosyu2000** [comment]
Make sure you include the issue number in the commit message. You can amend your previous commit message to add it in.

**Review by amosyu2000 — CHANGES_REQUESTED** [review]
Add the issue number to the commit message too, not just to the PR title.

**Review by MannyLemos — APPROVED** [review]
litty

**Review by amosyu2000 — APPROVED** [review]
LGTM!

**Pull request merged**
