### PR TITLE
[#36] Add NFR to SRS

### PR DESCRIPTION
**Pull request by aaronhsli**
Adding NFRs to the SRS

### CODE REVIEW

**Comment by aaronhsli** [comment]
Making this into a table.

**Review by MannyLemos — CHANGES_REQUESTED** [review]
I think we should use "CRA" instead of cyclops ride assist since we have defined the term

**Comment by aaronhsli** [comment]
Changed the names to CRA and made MD files.

**Review by MannyLemos — APPROVED** [review]

**Review by MannyLemos — APPROVED** [review]
great

**Review by amoscheung99527 — APPROVED** [review]

**Pull request merged**
